version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
